linters:
  enable-all: true
  disable:
    - contextcheck
    - exhaustivestruct # reports &Opts{} as an error
    - exhaustruct # reports &Opts{} as an error
    - gochecknoglobals
    - godox
    - golint # does not work with generics
    - ireturn # reports generic types as interfaces
    - lll
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
run:
  skip-files:
    - _test.go$
