language: go
sudo: false
go:
- 1.13.x
- tip
install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $(go env GOPATH)/bin v1.21.0
script:
- go test       -v ./...
- go test -race -v ./...
- golangci-lint run
