on: [push, pull_request]
name: Lint
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        run: |
          go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.1 run
